
# v.2
print('tes 123')
print('tes 456')

#checkpoint == com
#final 1.0 = commit

#git add . add to stage area
#git status
#git rm --cached namafile   untuk menghapus dari stage area
#git commit -m "*messages insert here*"
#git log commit history
#git log --oneline
#git checkout *insert commit id* buatliat2 doang liatny di git log oneline
#git checkout master kembali ke commit terakhir
#git reset 
